### ISSUE TITLE
update with illuminate/container 5.3  ?

### ISSUE THREAD

**Issue by imajim** [moon0326/artisan#3]
Hello ,

Possibly to update this GIT artisan to use it with  illuminate/container 5.3 ?

Best regards?

**Comment by avramovic** [comment]
Bump! I need it to work with illuminate/container 5.4 so maybe lock just to major version 5

**Comment by moon0326** [comment]
@imajim not sure how I missed this issue. Sorry for the delay. If you still need it, try version v1.6
